Run test on PHPUnit 9
clue/reactphp-http-proxy pull request #34
Opened 2020-06-16 09:54 UTC by SimonFrings

2020-06-17 20:15 UTC, clue requested changes

2020-06-17 20:15 UTC, clue commented on tests/ProxyConnectorTest.php
> +        $this->setExpectedException("InvalidArgumentException");
Nit: Can you update this to use single quotes instead of double quotes? (see also below)

2020-06-19 08:09 UTC, SimonFrings commented
Done Deal :+1:

2020-06-19 08:35 UTC, clue approved these changes
@SimonFrings Awesome, thanks for the update! :shipit:

2020-06-19 08:36 UTC, merged