Referencing reactphp/http instead of clue/reactphp-buzz in README
clue/reactphp-http-proxy pull request #35
Opened 2020-07-30 10:39 UTC by SimonFrings

2020-08-06 15:28 UTC, clue requested changes
@SimonFrings Thanks for the update, add some minor remarks below :shipit:

2020-08-06 15:28 UTC, clue commented on examples/01-http-request.php
> +// Make sure you're referencing the right proxy adress inside the ProxyConnector
```suggestion
// Make sure you're referencing the right proxy address inside the ProxyConnector
```

2020-08-06 15:28 UTC, clue commented on README.md
> +See also [ReactPHP's HTTP client](https://github.com/reactphp/http#client-usage) for more details.
```suggestion

See also [ReactPHP's HTTP client](https://github.com/reactphp/http#client-usage) for more details.
```

2020-08-06 15:28 UTC, clue commented on examples/11-proxy-raw-https-protocol.php
> +// world project, take a look at example-01
```suggestion
// world project, take a look at example #01 and https://github.com/reactphp/http#client-usage. 
```

?

2020-08-06 15:28 UTC, clue commented on examples/12-optional-proxy-raw-https-protocol.php
> +// world project, take a look at example-01
```suggestion
// world project, take a look at example #01 and https://github.com/reactphp/http#client-usage. 
```

?

2020-08-10 07:21 UTC, SimonFrings commented on examples/01-http-request.php
> +// Make sure you're referencing the right proxy adress inside the ProxyConnector
Done :+1:

2020-08-10 07:21 UTC, SimonFrings commented on README.md
> +See also [ReactPHP's HTTP client](https://github.com/reactphp/http#client-usage) for more details.
Done :+1:

2020-08-10 07:21 UTC, SimonFrings commented on examples/11-proxy-raw-https-protocol.php
> +// world project, take a look at example-01
Done :+1:

2020-08-10 07:21 UTC, SimonFrings commented on examples/12-optional-proxy-raw-https-protocol.php
> +// world project, take a look at example-01
Done :+1:

2020-09-08 10:27 UTC, Degra1991 approved these changes

2020-10-10 19:39 UTC, clue approved these changes
@SimonFrings Thanks for the update, changes LGTM! :shipit:

2020-10-10 19:39 UTC, merged